version: '3.9'

services:
  nats:
    image: nats:2.9.15-alpine
    command: ["-c", "/etc/nats/nats.conf"]
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
  server:
    build:
      context: server
      dockerfile: docker/Dockerfile
    depends_on:
      - nats
